baseurl = "https://tamaspapp.eu/"
languageCode = "en-us"
title = "Tamás K. Papp's website"
relativeURLs = true
# canonifyURLs = true
# disqusShortname = "tpappgithubio"
Copyright = "Copyright 2017, Tamás K. Papp. [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/legalcode)."
pygmentsStyle = "murphy"
pygmentsUseClasses = true
pygmentsCodefences = true
preserveTaxonomyNames = true

[author]
        name = "Tamás K. Papp"
        github = "tpapp"

[params]
        mathjax = true
        math = true

[blackfriday]
        extensionsmask = ["backslashLineBreak"]
